<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOOKSTORE [

<!ELEMENT BOOKSTORE (BOOK*) >
<!ELEMENT BOOK (BOOKID,BOOKTITLE,AUTHOR,PUBLISHED)>
<!ELEMENT BOOKID (#PCDATA)>
<!ELEMENT BOOKTITLE (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT PUBLISHED (#PCDATA)>
]>

<BOOKSTORE>
<BOOK>
<BOOKID> 01</BOOKID>
<BOOKTITLE>ART OF LIVING</BOOKTITLE>
<AUTHOR>SHANKAR</AUTHOR>
<PUBLISHED>2005 </PUBLISHED>
</BOOK>
<BOOK>
<BOOKID> 02</BOOKID>
<BOOKTITLE>DISCRETE MATH</BOOKTITLE>
<AUTHOR>KENNETH ROSEN</AUTHOR>
<PUBLISHED>1998 </PUBLISHED>
</BOOK>
<BOOK>
<BOOKID> 03</BOOKID>
<BOOKTITLE>HARRY POTTER</BOOKTITLE>
<AUTHOR>J.K.ROWLING</AUTHOR>
<PUBLISHED>2001 </PUBLISHED>
</BOOK>
</BOOKSTORE>