=== odileyandi-sir/wt/4th week/4b/4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="BOOKSTORE">
                        <xs:complexType>
                        <xs:sequence>
<xs:element name="BOOK" maxOccurs="unbounded">
<xs:complexType>
            <xs:sequence>
<xs:element name="BOOKID"       type="xs:string"></xs:element>
<xs:element name="AUTHOR"  type="xs:string"></xs:element>
<xs:element name="ISBN"    type="xs:string"></xs:element>
<xs:element name="publisher" type="xs:string"></xs:element>
<xs:element name="edition"  type="xs:int"></xs:element>
<xs:element name="price"     type="xs:decimal"></xs:element>
            </xs:sequence>
</xs:complexType>


</xs:element>
                       
  </xs:sequence>
     </xs:complexType>
           
  </xs:element>
</xs:schema>

=== odileyandi-sir/wt/4th week/4b/4.xml
<?xml version="1.0" encoding="utf-8"?>
<BOOKSTORE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\VAIBHAVI\Pictures\Saved Pictures\4.xsd">
  <BOOK>
    <BOOKID>abc</BOOKID>
    <AUTHOR>abc</AUTHOR>
    <ISBN>abc</ISBN>
    <publisher>abc</publisher>
    <edition>1</edition>
    <price>1</price>
  </BOOK>
  <BOOK>
    <BOOKID>abc</BOOKID>
    <AUTHOR>abc</AUTHOR>
    <ISBN>abc</ISBN>
    <publisher>abc</publisher>
    <edition>1</edition>
    <price>1</price>
  </BOOK>
</BOOKSTORE>
